### ISSUE TITLE
Search Data for real estate

### ISSUE THREAD

**Issue by kuj0210** [kuj0210/Regional-analyzer#12]
지금부터는 자료를 정리해서 이슈로게시
이슈는 작성자가아니라도 수정이가능
새로운 이슈를 만들고 

링크
해당내용 

형식으로 잘 정리할 것 필요한 내용들만 간추려서 쓸것, 라벨은 INFO

Element of PIMFY, NIMBY
data of station influence area and  real estate

님비, 핌피 현상의 요소 및 정도 
(예 초/중/고 등학교 모두 혐오시설이나 그중 중학교를 더 싫어했다)
역세권을 평가 관련 자료

**Comment by ras120** [comment]
감정평가 세부평가기준 - 한국감정원
2015 감정평가 세부평가기준_원문-PDF.pdf
대부분 내용은 어려움
이 자료의 144p 이후의 여러 표에서 각종 평가요인 목록을 참고하려함
[감정평가 세부평가기준_원문-PDF.pdf](https://github.com/kuj0210/Regional-analyzer/files/1810901/_.-PDF.pdf)

**Comment by ras120** [comment]
음...
[부동산가치의 분리방법.PDF](https://github.com/kuj0210/Regional-analyzer/files/1810941/default.PDF)

**Comment by ras120** [comment]
[복합용도부동산 감정평가기법에 관한 연구.pdf](https://github.com/kuj0210/Regional-analyzer/files/1810959/default.pdf)
http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=3c133c6010a9d3b2ffe0bdc3ef48d419#redirect

**Comment by ras120** [comment]
Simple Document
http://contents.kocw.or.kr/document/lec/2012/Sangmyung/ShimJaeYoung/12.pdf

**Comment by ras120** [comment]
NIMBY PIMFY 님비 핌피
https://prezi.com/nulqo4rhe6gd/nimby-pimfy/

**Comment by Kownby** [comment]
상권 분석 홈페이지 및 상권 분석방법 블로그

http://www.cigmagazine.com/single-post/2016/06/09/%EB%AC%B4%EB%A3%8C-%EC%83%81%EA%B6%8C%EB%B6%84%EC%84%9D%EC%82%AC%EC%9D%B4%ED%8A%B8-4%EA%B3%B3

https://brunch.co.kr/@an11778/9

**Comment by Kownby** [comment]
추가분 
http://webcache.googleusercontent.com/search?q=cache:5qu7AEmeb0UJ:www.semas.or.kr/common/download.kmdc%3Ff%3DUlvkQK9JKLudOtNTEElIBXbKU1yoYD6mRT0IJGyWs%252Fb47qpFZf9ctoSWJ2JP2gf%252B%250D%250A%26c%3D544+&cd=9&hl=ko&ct=clnk&gl=kr
